### ISSUE TITLE
Path Bug

### ISSUE THREAD

**Issue by stoyanovx** [HeresJohnny320/fivem-resource-file-watcher#1]
When the "Resource" folder is categorized like [BASE], [UTILITY] and etc. The auto_restart give error - [ script:auto_restart] Error: Resource Named:[utility] Is uninitialized or unknown for example ,if I found out a fix will publish it

**Comment by HeresJohnny320** [comment]
sorry for the late responds to be honest i forgot you can even make a category i will try to find a fix soon when i got time thanks for letting me know i hope we can resolve it soon but in the mean time you can use this in the main resource folder and that should work might also be a good idea to put any code that you are working on into the main resource folder as well then everything should work

**Comment by xChillax** [comment]
Made a PR to solve this issue. :)
